// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGddmeyTyQ_D6EXfyT-toNeXU-ZwIhZ8',
    appId: '1:717168770720:web:c8887de527d514d9aa93c5',
    messagingSenderId: '717168770720',
    projectId: 'myauthenticationproject-33966',
    authDomain: 'myauthenticationproject-33966.firebaseapp.com',
    storageBucket: 'myauthenticationproject-33966.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuRfbGsve0ymCFCXYO7o5SNP0mzfhKXHg',
    appId: '1:717168770720:android:035ed846ead8bf8baa93c5',
    messagingSenderId: '717168770720',
    projectId: 'myauthenticationproject-33966',
    storageBucket: 'myauthenticationproject-33966.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgUqkIMqo_4KMWprU5ITiSBP17ux4Ts50',
    appId: '1:717168770720:ios:0bd179e188fe1146aa93c5',
    messagingSenderId: '717168770720',
    projectId: 'myauthenticationproject-33966',
    storageBucket: 'myauthenticationproject-33966.appspot.com',
    iosBundleId: 'afaf.taskappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgUqkIMqo_4KMWprU5ITiSBP17ux4Ts50',
    appId: '1:717168770720:ios:e39d43aae277a9baaa93c5',
    messagingSenderId: '717168770720',
    projectId: 'myauthenticationproject-33966',
    storageBucket: 'myauthenticationproject-33966.appspot.com',
    iosBundleId: 'afaf.taskappfirebase.RunnerTests',
  );
}
